# this workflow will deploy the artifact to my Maven repository
name: Java CI with Maven and Deploy

on:
  release:
    types: [created]

  #run manually
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -B package

    - name: Deploy to Repository
      run: mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -B deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
        ACTION_PAT: ${{ secrets.ACTION_PAT }}
