#this workflow will publish a package to the
name: Java CI with Maven and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  #run manually
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        #server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        #settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -B package

    - name: Deploy to Repository
      run: mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -B deploy
      env:
        #GITHUB_TOKEN: ${{ github.token }}
        ACTION_PAT: ${{ secrets.ACTION_PAT }}
